<div class="contact-main-content">
<h3>Contacts Details</h3>
    <div class="phone-number">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/002-phone-receiver.svg'); ?>"/>
        <div>
            <label>(+995) 599 555 111</label>
            <p>(+995) 032 2 55 56 57</p>
        </div>
    </div>

    <div class="emails">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/024-email.svg'); ?>"/>
        <div>
            <label>vene@gmail.com</label>
            <p>vendor@gmail.com</p>
        </div>
    </div>



    <div class="contact-skype">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/003-skype-logo.svg'); ?>"/>
        <div>
            <label>vendor_contact</label>
            <p>vendor_support</p>
        </div>
    </div>
</div>


