<div style="display: block">
    <h3 style="color: white">Instagram</h3>
    <div>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/block.svg'); ?>"/>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/block.svg'); ?>"/>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/block.svg'); ?>"/>
    </div>
    <div>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/block.svg'); ?>"/>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/block.svg'); ?>"/>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/block.svg'); ?>"/>
    </div>
</div>
