<div class="payments">
    <div class="payment-info">
        <h4>100% secure & Trusted Payment.</h4>
        <p>Need help? Call us at +203-980-14-79 for any assistance required.</p>
    </div>
    <div class="payment-methods">
        <img style="padding-right: 25px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/mastercard.png'); ?>"/>
        <img style="padding-right: 25px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/paypal.png'); ?>"/>
        <img style="padding-right: 25px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/american_express.png'); ?>"/>
        <img style="padding-right: 25px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/maestro.png'); ?>"/>
        <img style="padding-right: 25px" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/visa.png'); ?>"/>
    </div>
</div>
