<body>
<ul class="main-content-tsintsadze">
    <li class="delivery">
        <img class="images" alt="photo" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/011-truck.svg'); ?>"/>
        <div class="free-delivery">
            <label class="free-delivery-label">FREE DELIVERY</label>
            <label>On orders over 100$</label>
        </div>
    </li>

    <li class="free-gift">
        <img class="images" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/003-gift.svg'); ?>"  alt="gift" />
        <div class="gifts">
            <label class="gift-label">CHOOSE A FREE GIFTS</label>
            <label>With every purchase</label>
        </div>
    </li>

    <li class="secure-shopping-content">
        <img class="images" src="<?php echo $this->getViewFileUrl('Magento_Theme::images/006-padlock.svg'); ?>"  alt="padlock" />
        <div class="secure-shopping">
            <label class="secure-shopping-label">100% SECURE SHOPPING</label>
            <label>mauris ac pulvinar</label>
        </div>
    </li>
</ul>
</body>
